#!/bin/bash

name=$1

mkdir $name

cd $name
ln -s ../resources/testlib.h .

mkdir statement
touch statement/legend.tex
touch statement/input.tex
touch statement/output.tex
cp ../resources/olymp.sty statement/
cp ../resources/problem.tex statement/
cp ../resources/statement.ftl statement/
cp ../resources/Makefile statement/
cp ../resources/master.tex statement/

cp ../compile .
cp ../resources/*.cpp .

cd ..
echo "Created:"
tree $name
