#!/bin/bash
clear; clear
g++ $1 -g -std=c++0x -Wall -Wconversion -Wshadow -I /usr/local/include -o ${1%.*} || exit

for i in *.in; do
    echo --- $i
    ./${1%.*} < $i > o && (diff -y -w o ${i%.in}.[ao]?? > t || cat t) || cat o
done
